.PHONY: all test update-modules

all:
	env GO111MODULE=on go build -v ./...

test:
	go test -race ./...
	go test -race -tags "sqlite_fts5 sqlite_vtable sqlite_trace sqlite_unlock_notify sqlite_preupdate_hook sqlite_column_metadata sqlite_math_functions sqlite_dbstat sqlite_percentile" ./...
	go vet ./...

update-modules:
	env GO111MODULE=on go get -u
	env GO111MODULE=on go mod tidy -v
