//go:build ignore

// Generate the C namespace without changing the bundled SQLCipher sources.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
)

func main() {
	api := regexp.MustCompile(`(?m)^SQLITE_API\b[^;{]*?\b((?:sqlite3|sqlcipher)\w*)\s*(?:\(|\[|;|=)`)
	helper := regexp.MustCompile(`\b(_sqlite3_\w+)\b`)
	names := make(map[string]bool)
	for _, pattern := range []string{"*.h", "*.c", "*.go"} {
		paths, err := filepath.Glob(pattern)
		if err != nil {
			panic(err)
		}
		for _, path := range paths {
			if strings.HasSuffix(path, "_test.go") || path == "sqlcipher_namespace.h" {
				continue
			}
			data, err := os.ReadFile(path)
			if err != nil {
				panic(err)
			}
			for _, re := range []*regexp.Regexp{api, helper} {
				for _, match := range re.FindAllSubmatch(data, -1) {
					names[string(match[1])] = true
				}
			}
		}
	}
	if !names["sqlite3_open_v2"] || !names["sqlite3_key"] || !names["_sqlite3_result_text"] {
		panic("missing required C API or helper declarations")
	}
	ordered := make([]string, 0, len(names))
	for name := range names {
		ordered = append(ordered, name)
	}
	slices.Sort(ordered)
	var out strings.Builder
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n#ifndef GO_SQLCIPHER_NAMESPACE_H\n#define GO_SQLCIPHER_NAMESPACE_H\n\n")
	for _, name := range ordered {
		condition := ""
		switch name {
		case "sqlite3_column_database_name", "sqlite3_column_database_name16", "sqlite3_column_table_name", "sqlite3_column_table_name16", "sqlite3_column_origin_name", "sqlite3_column_origin_name16":
			condition = "defined(SQLITE_ENABLE_COLUMN_METADATA)"
		case "sqlite3_profile", "sqlite3_trace":
			condition = "!defined(SQLITE_OMIT_DEPRECATED)"
		case "sqlite3_fts3_enable_parentheses":
			condition = "defined(SQLITE_TEST)"
		}
		if condition != "" {
			fmt.Fprintf(&out, "#if %s\n", condition)
		}
		fmt.Fprintf(&out, "#define %s gsc_%s\n", name, name)
		if condition != "" {
			out.WriteString("#endif\n")
		}
	}
	out.WriteString("\n#endif\n")
	if err := os.WriteFile("sqlcipher_namespace.h", []byte(out.String()), 0644); err != nil {
		panic(err)
	}
}
